name: golang-build-actions-workflow
on:
  push:
    # Sequence of patterns matched against refs/tags
    tags:
      - 'v*' # Push events to matching v*, i.e. v1.0, v20.15.10
      
permissions:
    contents: write

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        # Go 1.23 was the latest version as of 2024-08-31 but the action output a "warning":
        # Failed to restore: "/usr/bin/tar" failed with error: The process '/usr/bin/tar' failed with exit code 2
        # Go 1.22 didn't output the above "warning" so we're using this version.
        # Go 1.14 made -mod=vendor default.
        # Go 1.13 is the version set in go.mod.
        include:
          - { os: macos-14,     go: '1.22' }
          - { os: macos-14,     go: '1.21' }
          - { os: macos-14,     go: '1.20' }
          # Go 1.19 is the earliest version available for ARM64.
          - { os: macos-14,     go: '1.19' }
          # macos-12 runner has x86_64 support which is needed for old versions of Go
          - { os: macos-12,     go: '1.18' }
          - { os: macos-12,     go: '1.17' }
          - { os: macos-12,     go: '1.16' }
          - { os: macos-12,     go: '1.15' }
          - { os: macos-12,     go: '1.14' }
          - { os: macos-12,     go: '1.13' }
          - { os: ubuntu-22.04, go: '1.22', apt: libgtk-4-dev libwebkitgtk-6.0-dev }
          - { os: ubuntu-22.04, go: '1.22', apt: libgtk-3-dev libwebkit2gtk-4.1-dev }
          - { os: ubuntu-22.04, go: '1.22', apt: libgtk-3-dev libwebkit2gtk-4.0-dev }
          - { os: ubuntu-22.04, go: '1.21', apt: libgtk-3-dev libwebkit2gtk-4.1-dev }
          - { os: ubuntu-22.04, go: '1.20', apt: libgtk-3-dev libwebkit2gtk-4.1-dev }
          - { os: ubuntu-22.04, go: '1.19', apt: libgtk-3-dev libwebkit2gtk-4.1-dev }
          - { os: ubuntu-22.04, go: '1.18', apt: libgtk-3-dev libwebkit2gtk-4.1-dev }
          - { os: ubuntu-22.04, go: '1.17', apt: libgtk-3-dev libwebkit2gtk-4.1-dev }
          - { os: ubuntu-22.04, go: '1.16', apt: libgtk-3-dev libwebkit2gtk-4.1-dev }
          - { os: ubuntu-22.04, go: '1.15', apt: libgtk-3-dev libwebkit2gtk-4.1-dev }
          - { os: ubuntu-22.04, go: '1.14', apt: libgtk-3-dev libwebkit2gtk-4.1-dev }
          - { os: ubuntu-22.04, go: '1.13', apt: libgtk-3-dev libwebkit2gtk-4.1-dev }
          - { os: windows-2022, go: '1.22' }
          - { os: windows-2022, go: '1.21' }
          # Go 1.20 is the earliest version that is usable in this environment as of 2024-08-31.
          # Compilation fails with older versions:
          # [...]/bin/ld.exe: [...]\go-link-3209855222\000008.o: in function `x_cgo_thread_start':
          # \\_\_\runtime\cgo/gcc_util.c:18: undefined reference to `__imp___iob_func'
          - { image: windows-2022, go: '1.20' }
    name: Build (${{ matrix.os }}, go ${{ matrix.go }})
    steps:
      - uses: actions/checkout@v4

      - name: Install dependencies
        if: runner.os == 'Linux'
        run: sudo apt-get update && sudo apt-get install -y libwebkit2gtk-4.0-dev

      - uses: actions/setup-go@v5
        with:
          go-version: ${{ matrix.go }}

      - name: Build examples
        run: |
          go build
          
      - name: Archive Release
        uses: thedoctor0/zip-release@master
        with:
          type: 'zip'
          path: ${{ github.event.repository.name }}*
          filename: "${{ github.event.repository.name }}-${{ github.ref_name }}-${{ matrix.os }}.zip"
          
      - name: Release prebuilt
        uses: ncipollo/release-action@v1
        with:
          artifacts: "${{ github.event.repository.name }}-${{ github.ref_name }}-${{ matrix.os }}.zip"
          allowUpdates: true
          token: ${{ secrets.GITHUB_TOKEN }}
